### ISSUE TITLE
{Request] Update?

### ISSUE THREAD

**Issue by Immediate-Zero** [GothicIII/DJMaxRespectV-Randomizer#4]
Hello, I have just learned about this program and was wondering if you'd ever consider updating it include the newer songs on the list? Regardless, Thank you for this program!

**Comment by GothicIII** [comment]
Hi,

sure, give me at least 2 weeks since I am currently pretty busy with rl stuff. Also need to create (and purchase) the songdata first. I hope neowiz fixed the performance issues else the tool won't have constant results and be off sync with the game.

I sure appreciate that the tool has its use >)

**Comment by Immediate-Zero** [comment]
Have you been able to find time to work on this?

**Comment by GothicIII** [comment]
Yes I have :) 
i don't do git push until an update is finalized.
I tought it would be easy to update but here I am months later...

I still need to buy all new dlcs and I missed the last sale by a few hours... But thats not the main problem.

The tough part is that they release a song every season. Some will have access to the season-exclusive song but most of us won't. I have no intention to buy the premium pass and make an update every few weeks...
This costs time, because I have to include a menu that can directly edit the table entries from songdata[].
This is not a feature I had in mind back then and costs much time.

Last thing to fix is that I have to reorder the table entries to accomodate the game changes. There is still a lot to fix (race conditions, menu lag etc.) but I'm getting there.

I'll give you an update when I'm nearly finished. Hopefully it won't take so much time anymore.

Cheers

**Comment by Immediate-Zero** [comment]
Cool!  And no rush on this.  I find this program to be super useful, but you shouldn't burn yourself out on it.  

Also yeah, The DLC is best to be bought when it's on sale, no reason to buy most of these as full price when the sale prices can get to be really low.  Take your time on this, I've no problem being patient. (´◡`)

**Comment by Immediate-Zero** [comment]
Heyo!  Just giving a quicks heads-up that there is currently a sale on DJ MAX and it's DLCs!

**Comment by GothicIII** [comment]
Yes I finally bought them :) 

I am constantly working on the update. Here are some news:

1. I managed to get the chart crawler to work, so I am actually sitting on about 9000 difficulty data for charts. Still have to review that data since I doubt that I managed to improve it to over 99% accuracy.
2. It is a nightmare to rewrite most of the code. I never thought they would split collaboration songs. Pretty much every function broke because of that. This alone takes days xP
3. Gui and Settings are mostly done. Still issues with collab songs, though.
4. The main class for the song objects still needs to be updates for the collab split. This will be my next goal.
5. Sadly this is the most difficult part. The sorting of the internal songobjects. Experience shows that with every added song they manage either to break the ordering of a char or simple use double named songs and then the ordering will be off. This can take from hours to weeks.

 Still have no clue how to implement Clear pass premium songs. Are they really added afterwards as normal content?

I'll try my best with the limited time I have, but I'm positive to release it soon.

![Unbenannt](https://github.com/user-attachments/assets/85304331-b1e7-42c3-bdd7-bc7dffb543a2)

I just updated the songlist.db
If you want, you can help me by looking for errors (e.g. spelling mistakes or wrong difficutly). This is the structure of the lines:
songname;songpack;4nm;4hd;4mx;4sc;5nm;5hd;[...]

**Comment by Immediate-Zero** [comment]
[DJMAX SongNames Check.txt](https://github.com/user-attachments/files/17603340/DJMAX.SongNames.Check.txt)

I looked through all the songs and these are the Spelling Errors that I found.  I'm not sure if Case Sensitivity or Spaces Matter, but I marked those as well.

**Comment by GothicIII** [comment]
I've done the main thing, finally. Thank you for your work, I'll implement the changes within the stable release. => I have to test the memdb against it first. 
I haven't touched the sorting algorithm, so I don't know if the memdb has the right order. Thats on Todo.

I'm taking a break now for a week or so. I pushed hard through the last days xD 

Bonus:
I've prepared an alpha. There are surely bugs I need to find but maybe it works?

Instructions:
rename to .ahk and Download ahkv2. Drag the file onto the ahk.exe. Make sure songlist.db is in the same directory.
[DJMaxRandomizer.txt](https://github.com/user-attachments/files/17604335/DJMaxRandomizer.txt)

**Comment by GothicIII** [comment]
Alright. Update is done. Took a while but at least the core functionality is back :)

**Comment by Immediate-Zero** [comment]
Awesome!  Can't wait to try it out!

**Comment by Immediate-Zero** [comment]
After testing it out for a while, it works great!  It landed on the correct song every time and I didn't run into any errors.  Great Job on this!  Thanks a ton for the update ~♫
